 
message("Running non-parametric estimation data cens1910")

###  verb <- user.prompt()
message("Loading the data sample")
res <- data(cens1910)
###eidemopar(in90,tind=3,xind=1,nind=5,invn=TRUE)
###res <- get(res, env=environment())
t <- cens1910[[1]]
x <- cens1910[[2]]
tvap <- cens1910[[3]]

###ind <- which(x <= 0 | x >= 1 |t <= 0 | t >= 1 |tvap<=0)
ind <- which(x<0 | x>1 | t <= 0 | t >= 1 |tvap<=0)
if(length(ind)){
  ind <- unique.default(ind)
  x <- x[-ind]
  t <- t[-ind]
  tvap <- tvap[-ind]
}
x[x<=0] <- .Machine$double.eps
x[x>=1] <- 1-.Machine$double.eps
n <- round(tvap)

message("Running non-parametric estimation")
dbuf <- ei(t,x,n,1,1,EnonPar=1,dbug=FALSE)
print(names(dbuf))
message("Obtaining overall beta's and std errors")
berr <- eiread(dbuf,"paggs")
print(berr)
message("Running non-parametric estimation")
dbuf <- ei(t,x,n,1,1,EnonPar=1,dbug=FALSE)
print(names(dbuf))
message("Obtaining beta blacks")  
betab <- dbuf$betabs
message("Calculating beta whites")
betaw <- betab2w(t,x,betab)
message("Obtaining overall beta's and std errors")
berr <- eiread(dbuf,"paggs")
print(berr)               
message("Running graphics:")
user.prompt()
eigraph(dbuf,"tomog")
user.prompt()
eigraph(dbuf,"tomogp")
user.prompt()
eigraph(dbuf,"tomoge")
user.prompt()
eigraph(dbuf,"tomogci")
user.prompt()
eigraph(dbuf,"tomogci95")
user.prompt()
eigraph(dbuf,"estsims")
user.prompt()
eigraph(dbuf,"tomogs")
user.prompt()
eigraph(dbuf,"nonpar")
user.prompt()
eigraph(dbuf,"xtc")
user.prompt()
eigraph(dbuf,"xt")
user.prompt()
eigraph(dbuf,"xgraph")
user.prompt()
eigraph(dbuf,"xgraphc")
user.prompt()
eigraph(dbuf,"goodman")
user.prompt()
eigraph(dbuf,"profile")
user.prompt()
eigraph(dbuf,"profileR")
user.prompt()
eigraph(dbuf,"postb")
user.prompt()
eigraph(dbuf,"postW")
user.prompt()
eigraph(dbuf,"post")
user.prompt()
message("Running beta with kern=E")
eigraph(dbuf,"betaB")
user.prompt()
eigraph(dbuf,"betaW")
user.prompt()
eigraph(dbuf,"beta")
user.prompt()
message("Running beta with kern=TN")
eigraph(dbuf,"beta",kern="TN")
user.prompt()
eigraph(dbuf,"results", kern="E")
user.prompt()
eigraph(dbuf,"lines")
user.prompt()
eigraph(dbuf,"bivar")
user.prompt()
eigraph(dbuf,"betabw")
user.prompt()
eigraph(dbuf,"biasb")
user.prompt()
eigraph(dbuf,"biasw")
user.prompt()
eigraph(dbuf,"bias")
user.prompt()
eigraph(dbuf,"boundxb")
user.prompt()
eigraph(dbuf,"boundxw")
user.prompt()
eigraph(dbuf,"boundx")
user.prompt()
eigraph(dbuf,"movie")
user.prompt()
eigraph(dbuf,"movied")
user.prompt()
message("Addition: dependences of beta's vs T,N")
eigraph(dbuf,"betast")
user.prompt()
eigraph(dbuf,"betasn")
user.prompt()
message("Addition: three-dimensional dependences of beta's vs X,T,N")
eigraph(dbuf,"betaxn")
user.prompt()
eigraph(dbuf,"betatn")





