message("Running parametric estimation:Ecdfbvn=6 data cens1910")
 
###  verb <- user.prompt()
message("Loading the data sample")
res <- data(cens1910)
res <- get(res, env=environment())
###eidemopar(res,tind=3,xind=1,nind=5,invn=TRUE)
t <- cens1910[[1]]
x <- cens1910[[2]]
tvap <- cens1910[[3]]
truthB <- cens1910[[4]]
truthW <- cens1910[[5]]
truth <- cbind(truthB,truthW)
colnames(truth) <- c("truthB", "truthW")

xind <- which(x < 0 | x > 1)
tind <- which(t <= 0 | t >= 1)
nind <- which(tvap<=0)
ind <- unique.default(c(xind,tind,nind))
if(length(ind)) {
  message("Deleting the following precint indexes...")
  print(ind)
  x <- x[-ind]
  t <- t[-ind]
  tvap <- tvap[-ind]
  truth <- truth[-ind,]
}
x[x<=0] <- .Machine$double.eps
x[x>=1] <- 1-.Machine$double.eps
n <- round(tvap)

message("Running default parametric estimation")
###user.prompt()
dbuf <- ei(t,x,n,1,1,EdoML=1,dbug=FALSE)
dbuf$truth <- truth
print(names(dbuf))
message("Obtaining overall beta's and std errors")
berr <- eiread(dbuf,"paggs")
print(berr)
message("Running graphics:")
user.prompt()
eigraph(dbuf,"tomog")
user.prompt()
eigraph(dbuf,"tomogp")
user.prompt()
eigraph(dbuf,"tomoge")
message("Running truth with tomograpy....")
user.prompt()
eigraph(dbuf,"tomogt")
user.prompt()
eigraph(dbuf,"tomogci")
user.prompt()
eigraph(dbuf,"tomogci95")
user.prompt()
eigraph(dbuf,"estsims")
user.prompt()
eigraph(dbuf,"tomogs")
user.prompt()
eigraph(dbuf,"nonpar")
user.prompt()
eigraph(dbuf,"xtc")
user.prompt()
eigraph(dbuf,"xt")
user.prompt()
eigraph(dbuf,"xgraph")
user.prompt()
eigraph(dbuf,"xgraphc")
user.prompt()
eigraph(dbuf,"goodman")
user.prompt()
eigraph(dbuf,"xtfit")
user.prompt()
eigraph(dbuf,"xtfitg")
user.prompt()
eigraph(dbuf,"fit")
user.prompt()
message("Running fitt with truth...")
eigraph(dbuf,"fitt")
user.prompt()
eigraph(dbuf,"profile")
user.prompt()
eigraph(dbuf,"profileR")
user.prompt()
eigraph(dbuf,"postb")
user.prompt()
eigraph(dbuf,"postW")
user.prompt()
eigraph(dbuf,"post")
user.prompt()
message("Running beta with kern=E")
eigraph(dbuf,"betaB")
user.prompt()
eigraph(dbuf,"betaW")
user.prompt()
message("Running beta with kern=E")
eigraph(dbuf,"beta")
user.prompt()
message("Running beta with kern=TN")
eigraph(dbuf,"beta",kern="TN")
user.prompt()
eigraph(dbuf,"results",kern="E")
user.prompt()
message("Running prectb with truth")
eigraph(dbuf,"prectb")
user.prompt()
user.prompt()
message("Running prectw with truth")
eigraph(dbuf,"prectw")
user.prompt()
message("Running truth")
eigraph(dbuf,"truth")
user.prompt()
eigraph(dbuf,"lines")
user.prompt()
message("Running tlines with truth")
eigraph(dbuf,"tlines")
user.prompt()
user.prompt()
eigraph(dbuf,"bivar")
user.prompt()
message("Running tbivar with truth")
eigraph(dbuf,"tbivar")
user.prompt()
eigraph(dbuf,"betabw")
user.prompt()
message("Running ptileb with truth")
eigraph(dbuf,"ptileb")
user.prompt()
message("Running ptilew with truth")
eigraph(dbuf,"ptilew")
user.prompt()
message("Running ptile with truth")
eigraph(dbuf,"ptile")
user.prompt()
message("Running simsb with truth")
eigraph(dbuf,"simsb")
user.prompt()
message("Running simsw with truth")
eigraph(dbuf,"simsw")
user.prompt()
message("Running sims with truth")
eigraph(dbuf,"sims")
user.prompt()
eigraph(dbuf,"biasb")
user.prompt()
eigraph(dbuf,"biasw")
user.prompt()
eigraph(dbuf,"bias")
user.prompt()
message("Running tbiasb with truth")
eigraph(dbuf,"tbiasb")
user.prompt()
message("Running tbiasw with truth")
eigraph(dbuf,"tbiasw")
user.prompt()
message("Running bias with truth")
eigraph(dbuf,"bias")
user.prompt()
eigraph(dbuf,"boundxb")
user.prompt()
eigraph(dbuf,"boundxw")
user.prompt()
eigraph(dbuf,"boundx")
user.prompt()
eigraph(dbuf,"movie")
user.prompt()
eigraph(dbuf,"movied")
user.prompt()
message("Addition: dependences of beta's vs T,N")
eigraph(dbuf,"betast")
user.prompt()
eigraph(dbuf,"betasn")
user.prompt()
message("Addition: three-dimensional dependences of beta's vs X,T,N")
eigraph(dbuf,"betaxn")
user.prompt()
eigraph(dbuf,"betatn")














