message("Running parametric estimation:Ecdfbvn=6 data pa90")
 
###  verb <- user.prompt()
message("Loading the data sample")
res <- data(pa90)
###eidemopar(res,tind=3,xind=1,nind=5,invn=TRUE)
t <- pa90[[3]]
x <- pa90[[1]]
invtvap <- pa90[[5]]
tvap <- 1/(invtvap +.Machine$double.eps)
xind <- which(x < 0 | x > 1)
tind <- which(t <= 0 | t >= 1)
nind <- which(tvap<=0)
ind <- unique.default(c(xind,tind,nind))
if(length(ind)) {
  message("Deleting the following precint indexes...")
  print(ind)
  x <- x[-ind]
  t <- t[-ind]
  tvap <- tvap[-ind]
}
x[x<=0] <- .Machine$double.eps
x[x>=1] <- 1-.Machine$double.eps
n <- round(tvap)
message("Running default parametric estimation")
###user.prompt()
dbuf <- ei(t,x,n,1,1,EdoML=1,dbug=FALSE)
print(names(dbuf))
message("Obtaining overall beta's and std errors")
berr <- eiread(dbuf,"paggs")
print(berr)
message("Running graphics:")
user.prompt()
eigraph(dbuf,"tomog")
user.prompt()
eigraph(dbuf,"tomogp")
user.prompt()
eigraph(dbuf,"tomoge")
user.prompt()
eigraph(dbuf,"tomogci")
user.prompt()
eigraph(dbuf,"tomogci95")
user.prompt()
eigraph(dbuf,"estsims")
user.prompt()
eigraph(dbuf,"tomogs")
user.prompt()
eigraph(dbuf,"nonpar")
user.prompt()
eigraph(dbuf,"xtc")
user.prompt()
eigraph(dbuf,"xt")
user.prompt()
eigraph(dbuf,"xgraph")
user.prompt()
eigraph(dbuf,"xgraphc")
user.prompt()
eigraph(dbuf,"goodman")
user.prompt()
eigraph(dbuf,"xtfit")
user.prompt()
eigraph(dbuf,"xtfitg")
user.prompt()
eigraph(dbuf,"fit")
user.prompt()
eigraph(dbuf,"profile")
user.prompt()
eigraph(dbuf,"profileR")
user.prompt()
eigraph(dbuf,"postb")
user.prompt()
eigraph(dbuf,"postW")
user.prompt()
eigraph(dbuf,"post")
user.prompt()
message("Running beta with kern=E")
eigraph(dbuf,"betaB")
user.prompt()
eigraph(dbuf,"betaW")
user.prompt()
eigraph(dbuf,"beta")
user.prompt()
message("Running beta with kern=TN")
eigraph(dbuf,"beta",kern="TN")
user.prompt()
eigraph(dbuf,"results",kern="E")
user.prompt()
eigraph(dbuf,"lines")
user.prompt()
eigraph(dbuf,"bivar")
user.prompt()
eigraph(dbuf,"betabw")
user.prompt()
eigraph(dbuf,"biasb")
user.prompt()
eigraph(dbuf,"biasw")
user.prompt()
eigraph(dbuf,"bias")
user.prompt()
eigraph(dbuf,"boundxb")
user.prompt()
eigraph(dbuf,"boundxw")
user.prompt()
eigraph(dbuf,"boundx")
user.prompt()
eigraph(dbuf,"movie")
user.prompt()
eigraph(dbuf,"movied")
user.prompt()
message("Addition: dependences of beta's vs T,N")
eigraph(dbuf,"betast")
user.prompt()
eigraph(dbuf,"betasn")
user.prompt()
message("Addition: three-dimensional dependences of beta's vs X,T,N")
eigraph(dbuf,"betaxn")
user.prompt()
eigraph(dbuf,"betatn")














